services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        ports:
            - "80:80"
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
    odoo:
        image: virgiliosantos/mettric-enterprise
        ports:
            - "8069:8069"
        links:
            - db
        environment:
            - VIRTUAL_HOST=mettric.local    
            - VIRTUAL_PORT=8069
        volumes:
            - ./custom:/home/odoo/custom
            - mettric-odoo-filestore:/home/odoo/data
    db:
        image: postgres
        environment:
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
        volumes:
            - mettric-database:/var/lib/postgres/data
volumes:
    mettric-database:
    mettric-odoo-filestore:

version: '2'
